name: Local .NET Core CI/CD

jobs:
  build:
    steps:
      - name: Checkout code
        run: git clone https://github.com/Sandeep1696/sandeep.git

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o 'C:\Users\PRAX\Deploying_Folder'

      - name: Create Deployment Folder
        run: mkdir 'C:\Users\PRAX\Deploying_Folder'

      - name: Copy files to deployment folder
        run: |
          copy /Y "path\to\your\project\out\*" "C:\Users\PRAX\Deploying_Folder"
